# Generated by Django 5.2.15 on 2026-06-13 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("panel", "Panel"), ("api", "API")], max_length=10
                    ),
                ),
                ("request_limit", models.PositiveIntegerField(default=5000)),
                ("price_cents", models.PositiveIntegerField(default=3000)),
                ("is_active", models.BooleanField(default=True)),
                ("used", models.PositiveIntegerField(default=0)),
                (
                    "period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["plan"],
                "unique_together": {("user", "plan")},
            },
        ),
    ]
