# Generated by Django 5.2.15 on 2026-06-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(
                default=False,
                help_text="Reserved: auto-renew + bill at period end (not active yet).",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reserved: external payment/gateway reference (not active yet).",
                max_length=128,
            ),
        ),
    ]
