# Generated by Django 5.2.15 on 2026-06-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_auto_renew_subscription_payment_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "plan",
                    models.CharField(
                        choices=[("panel", "Panel"), ("api", "API")],
                        help_text="Which meter this package applies to (panel or API).",
                        max_length=10,
                    ),
                ),
                (
                    "request_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Requests allowed per period. Leave blank for UNLIMITED.",
                        null=True,
                    ),
                ),
                ("price_cents", models.PositiveIntegerField(default=3000)),
                ("period_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["plan", "price_cents", "name"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="period_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="request_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=5000,
                help_text="Requests per period. NULL = unlimited (still counted).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="billing.package",
            ),
        ),
    ]
