# Generated by Django 5.2.15 on 2026-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkjob",
            name="webhook_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulkjob",
            name="webhook_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
