# Generated by Django 5.2.15 on 2026-06-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rate_limit_per_min",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Requests per minute before HTTP 429 (0 = unlimited).",
            ),
        ),
    ]
