# Generated by Django 5.2.15 on 2026-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="can_manage_accounts",
            field=models.BooleanField(
                default=False,
                help_text="May manage the upstream Midasbuy bot accounts.",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="can_order",
            field=models.BooleanField(
                default=False, help_text="May look up players and redeem (panel + API)."
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="can_use_api",
            field=models.BooleanField(
                default=False,
                help_text="May create API keys and call the API directly.",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("staff", "Staff"), ("client", "Client")],
                default="client",
                max_length=10,
            ),
        ),
    ]
