# Generated by Django 5.2.15 on 2026-06-16 08:45

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_client_refs(apps, schema_editor):
    """Give every existing user a unique client_ref before the UNIQUE constraint
    is applied (a plain AddField would leave them all '' and collide)."""
    User = apps.get_model("apiauth", "User")
    existing = set(
        User.objects.exclude(client_ref="").values_list("client_ref", flat=True)
    )
    for user in User.objects.filter(client_ref="").iterator():
        ref = "cl_" + secrets.token_hex(8)
        while ref in existing:
            ref = "cl_" + secrets.token_hex(8)
        existing.add(ref)
        user.client_ref = ref
        user.save(update_fields=["client_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("apiauth", "0002_user_rate_limit_per_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_ips",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional allow-list of IPs/CIDRs (comma or newline separated). Empty = allow any source IP.",
            ),
        ),
        # Step 1: add the column WITHOUT the unique constraint so existing rows can
        # share the empty default momentarily.
        migrations.AddField(
            model_name="user",
            name="client_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Identifier the partner sends (X-Client-Id) to select this client.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the partner that owns this client.",
                limit_choices_to={"role": "partner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("client", "Client"),
                    ("partner", "Partner"),
                ],
                default="client",
                max_length=10,
            ),
        ),
        # Step 2: backfill unique refs for existing rows.
        migrations.RunPython(populate_client_refs, migrations.RunPython.noop),
        # Step 3: now it's safe to enforce uniqueness.
        migrations.AlterField(
            model_name="user",
            name="client_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifier the partner sends (X-Client-Id) to select this client.",
                max_length=40,
                unique=True,
            ),
        ),
    ]
