# Generated by Django 5.2.14 on 2026-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MidasbuyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Friendly name for this account", max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Logged Out"),
                            (1, "Logged In"),
                            (2, "Login Failed"),
                            (3, "Session Expired"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "session_dir",
                    models.CharField(
                        blank=True,
                        help_text="Path to folder with storage_state.json + cookies.json",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
