# Generated by Django 5.2.14 on 2026-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="midasbuyaccount",
            name="cookie_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="session_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="storage_state_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="storage_state_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="token_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="midasbuyaccount",
            name="session_dir",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="MidasbuyLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "screenshot_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "html_snapshot_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_attempts",
                        to="accounts.midasbuyaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
