# Generated by Django 5.2.15 on 2026-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_midasbuyaccount_cookie_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="midasbuyaccount",
            name="consecutive_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="midasbuyaccount",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
