from pydantic import BaseModel, Field


# ── Inbound requests (from the user / your Django form / your frontend) ──────

class PlayerLookupRequest(BaseModel):
    player_id: str = Field(..., description="PUBG Mobile player UID")
    country_code: str = Field("bd", description="ISO country code, e.g. 'bd', 'us'")


class RedeemRequest(BaseModel):
    player_id: str = Field(..., description="PUBG Mobile player UID")
    pin_code: str = Field(..., description="UC redeem / pin code")
    country_code: str = Field("bd", description="ISO country code")


# ── Outbound API payloads (sent to Midasbuy after encryption) ────────────────

class EncryptedEnvelope(BaseModel):
    """
    The three fields that replace a raw payload in any Midasbuy API call.
    Generated by build_encrypted_payload() in crypto.py.
    """
    encrypt_msg: str
    ctoken_ver: str
    ctoken: str


# ── Responses returned to the caller ─────────────────────────────────────────

class PlayerInfo(BaseModel):
    player_id: str
    username: str
    role_id: str = ""
    server_id: str = ""
    zone_id: str = ""


class PlayerLookupResponse(BaseModel):
    success: bool
    player: PlayerInfo | None = None
    error: str | None = None


class RedeemResponse(BaseModel):
    success: bool
    message: str
    raw: dict | None = None
